import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'

export default function PageLayout({ children, title }) {
	return (
		<>
			<Head>
				<title>{`News App | ${title}`}</title>
				<meta name='description' content='News app generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💻</text></svg>'
				></link>
			</Head>
			<Header />
			<main>{children}</main>
			<Footer />
		</>
	)
}
